let pessoas = [
    'Ana Silva',
    'Carlos Oliveira',
    'Mariana Santos',
    'Rafael Pereira',
    'Isabel Lima',
    'Bruno Costa',
    'Laura Fernandes',
    'Rodrigo Souza',
    'Amanda Oliveira',
    'Felipe Martins',
    'Camila Pereira',
    'Lucas Silva',
    'Juliana Santos',
    'Diego Oliveira',
    'Fernanda Lima',
    'Gustavo Costa',
    'Patrícia Fernandes',
    'Vinícius Souza',
    'Renata Martins',
    'Daniel Lima',
    'Carolina Oliveira',
    'Pedro Santos',
    'Larissa Costa',
    'Thiago Fernandes',
    'Lívia Souza',
    'José Martins',
    'Beatriz Silva',
    'Gabriel Pereira',
    'André Oliveira',
    'Raquel Lima',
    'Leonardo Costa',
    'Natália Fernandes',
    'Eduardo Souza',
    'Luiza Martins',
    'Ricardo Lima',
    'Gabriela Silva',
    'Hugo Pereira',
    'Vanessa Oliveira',
    'Marcelo Santos',
    'Larissa Fernandes',
    'Lucas Costa',
    'Aline Souza',
    'Matheus Martins',
    'Manuela Lima',
    'Antônio Silva',
    'Bianca Pereira',
    'Fernando Oliveira',
    'Isabella Santos',
    'Roberto Fernandes',
    'Clara Souza',
    'Miguel Martins',
    'Ana Luiza Lima',
    'Guilherme Costa',
    'Paula Oliveira',
    'Joaquim Santos',
    'Natalia Fernandes',
    'Pedro Lima',
    'Carla Silva',
    'Marcos Pereira',
    'Catarina Oliveira',
    'Fábio Souza',
    'Tatiane Martins',
    'Anderson Lima',
    'Mariana Silva',
    'Luiz Costa',
    'Renata Oliveira',
    'Vinícius Santos',
    'Isabela Fernandes',
    'Rafaela Souza',
    'Daniel Martins',
    'Julia Lima',
    'Thiago Costa',
    'Letícia Pereira',
    'Luciana Oliveira',
    'Victor Fernandes',
    'Alice Souza',
    'Gabriel Martins',
    'Lívia Lima',
    'Roberto Costa',
    'Camila Oliveira',
    'José Pereira',
    'Amanda Fernandes',
    'Diego Souza',
    'Mariana Costa',
    'Ricardo Oliveira',
    'Natália Lima',
    'Felipe Costa',
    'Carolina Fernandes',
    'André Souza',
    'Laura Martins',
    'Gustavo Lima',
    'Lara Oliveira',
    'Bruno Fernandes',
    'Juliano Pereira',
    'Luana Silva',
    'Lucas Oliveira',
    'Mariana Souza',
    'Thiago Lima'
  ]

function sortear() {
    let nump = pessoas.length
    let nums = Math.floor(Math.random() * nump)

    document.getElementById('psort').innerHTML = pessoas[nums]
}